package com.jstudio.jkit

object MimeType {
    const val DOC = "application/msword"
    const val BIN = "application/octet-stream"
    const val EXE = "application/octet-stream"
    const val PDF = "application/pdf"
    const val RTF = "application/rtf"
    const val XLS = "application/vnd.ms-excel"
    const val PPT = "application/vnd.ms-powerpoint"
    const val TGZ = "application/x-compressed"
    const val GZ = "application/x-gzip"
    const val ZIP = "application/zip"
    const val MP3 = "audio/mpeg"
    const val AAC = "audio/aac"
    const val WAV = "audio/x-wav"
    const val PNG = "image/png"
    const val BMP = "image/bmp"
    const val GIF = "image/gif"
    const val JPEG = "image/jpeg"
    const val TIFF = "image/tiff"
    const val ICO = "image/x-icon"
    const val HTML = "text/html"
    const val TXT = "text/plain"
    const val RTX = "text/richtext"
    const val MPEG = "video/mpeg"
    const val MP4 = "video/mp4"
    const val MOV = "video/quicktime"
    const val AVI = "video/x-msvideo"
    const val DOCX = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    const val XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    const val PPTX = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
}